//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string SystemName { get; set; }
        public string IssueType { get; set; }
        public string ClassName { get; set; }
        public string MethodName { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> RequestNumber { get; set; }
        public Nullable<int> RequestName { get; set; }
        public Nullable<int> Status { get; set; }
        public string Comment { get; set; }
        public string Error { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModefiedDate { get; set; }
        public string ModefiedBy { get; set; }
    
        public virtual User_Information User_Information { get; set; }
        public virtual Status Status1 { get; set; }
        //public List<UpdateViewCompanyDto> Requestdropdown { get; set; }
    }
}
